export const wonderMailText = {
    FriendRescue: "Friend Rescue",
    RescueType0: "Help me.",
    RescueType1: "Find XXPKMN.",
    RescueType2: "Escort to XXPKMN.",
    RescueType3: "Find XXITEM.",
    RescueType4: "Deliver XXITEM.",
    BasementFloor: "BXXF",
    AboveGroundFloor: "XXF",
    SpecialMission: "Special mission",
    ChooseClient: "Please choose a client.",
    ChooseTarget: "Please choose a target Pokemon.",
    ChooseItem: "Please choose an item to find or deliver.",
    ItemNotFound: "The XX can't be found in the YY dungeon.",
    FriendAreaError: "To receive a Friend Area reward, the mission must have at least D difficulty.",
    InvalidPassword: "The password is invalid.",
    FriendAreaReward: "Friend Area [XX].",
    NearPlace: "Near XX",
    DifficultyLine: "Difficulty:",
    PlusReward: "XX + ?",
    PlusRewardBrackets: "XX + ? [YY]",
    RewardLine: "Reward:",
    PlaceLine: "Place:",
    ClientLine: "Client:",
    ObjectiveLine: "Objective:",
    WonderMailLine: "Wonder Mail:",
};
